version: '3'
services:

  app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "8080:8080"
    working_dir: /app

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    container_name: api

  db:
    image: mysql:5.7.22
    container_name: db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: employesmanager
      MYSQL_ROOT_PASSWORD: rali@1992
    volumes:
      - dbdata:/var/lib/mysql/

volumes:
  dbdata: